"""Add purchased field and purchase_date to SavingsGoal

Revision ID: 2a3ae768d439
Revises: 8542cdd3431a
Create Date: 2025-05-01 14:34:24.757728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3ae768d439'
down_revision = '8542cdd3431a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_goal', schema=None) as batch_op:
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('purchased')

    # ### end Alembic commands ###
