"""Add SavingsDeposit model and update SavingsGoal

Revision ID: 4f7868ed03ba
Revises: af1e63fff67e
Create Date: 2025-04-28 21:59:50.692383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7868ed03ba'
down_revision = 'af1e63fff67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_deposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('savings_goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['savings_goal_id'], ['savings_goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savings_deposit')
    # ### end Alembic commands ###
