"""Added hourly wage tracking

Revision ID: 9f2ab928d702
Revises: 48004136e166
Create Date: 2025-04-21 13:36:36.136612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2ab928d702'
down_revision = '48004136e166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hourly_wage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hours_per_week', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('hours_per_week')
        batch_op.drop_column('hourly_wage')

    # ### end Alembic commands ###
